version: '3.8'

services:
  ecommerce-product:
    image: ${REGISTRY_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
    container_name: ecommerce-product-service-container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      - "3001:3001"
    networks:
      - ecommerce-net
    depends_on:
      ecommerce-db:
        condition: service_healthy

networks:
  ecommerce-net:
    name: ecommerce-net
    driver: bridge